import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="w-full bg-gray-100 border-b border-gray-300 py-4 mb-8">
          <div className="container mx-auto flex justify-center gap-8">
            <a href="/login/patient/login" className="text-blue-700 hover:underline font-medium">Patient Login</a>
            <a href="/login/doctor/login" className="text-teal-700 hover:underline font-medium">Doctor Login</a>
            <a href="/login/hospital/login" className="text-pink-700 hover:underline font-medium">Admin Login</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
